open-atmos/PySDM

- PySDM/backends/numba/condensation_methods.py
- PySDM/simulation/particles_builder.py
- PySDM_examples/ICMW_2012_case_1/simulation.py
- PySDM_examples/Yang_et_al_2018_Fig_2/demo.ipynb
- PySDM_examples/Yang_et_al_2018_Fig_2/example.py
- PySDM_examples/Yang_et_al_2018_Fig_2/setup.py
- PySDM_tests/smoke_tests/Yang_et_al_2018_Fig_2/test_just_do_it.py
sanitized test__just_do_it in Yang
> added adaptiveness flag to condensation methods/make_condensation_solver

- PySDM_examples/Shima_et_al_2009_Fig_2/demo.ipynb
- PySDM_examples/Shima_et_al_2009_Fig_2/spectrum_plotter.py
> more TODOs

- PySDM/backends/thrustRTC/fakeThrustRTC/fakeThrustRTC.py
- PySDM/backends/thrustRTC/impl/_algorithmic_methods.py
- PySDM_tests/unit_tests/backends/storage/test_indexed_storage.py
> fixed _sort_by_cell_id_and_update_cell_start

- PySDM/dynamics/coalescence/coalescence.py
- PySDM/dynamics/coalescence/random_generator_optimizer.py
- PySDM_tests/unit_tests/dynamics/coalescence/test_sdm_single_cell.py
coalescence adaptivity spatial enhancement preludium
> Coalescence refactor

- PySDM/backends/thrustRTC/impl/_algorithmic_methods.py
Regarding #246, we want to get rid of the kludge 
@kyetuur
> add thurstRTC moments

- .github/workflows/main.yml
- PySDM/dynamics/condensation.py
- PySDM_examples/Bartman_et_al_2021/demo.ipynb
- PySDM_tests/smoke_tests/Yang_et_al_2018_Fig_2/test_just_do_it.py
- README.md
setting default condensation tolerances to 1e-6
using default condensation tolerance in Bartman_et_al_2021 example
remove obsolte pip uninstall intel-tbb from Github Actions workflow
fix link & elaborate on pip vs. git installation
TRAVIS -> CI env var fix in test_just_do_it.py
> new default condensation tolerance, cleanups

- PySDM_examples/Jaruga_and_Pawlowska_2018/demo.ipynb
- PySDM_examples/Kreidenweis_et_al_2003/simulation.py
This is work in progress on reproducing figure 2 from Jaruga_and_Pawlowska_2018. It includes s_max(n_sd) and cloud_droplet_number(n_sd) plots in jupyter notebook
> wip on Fig2 from Jaruga_and_Pawlowska_2018

- PySDM/exporters/__init__.py
- PySDM/exporters/vtk_exporter.py
- PySDM_tests/smoke_tests/Arabas_et_al_2015/test_export.py
- setup.py
- test-time-requirements.txt
vtk exporter for Particles + test
> Vtk exporter

- PySDM/physics/diffusion_kinetics/__init__.py
- PySDM/physics/diffusion_kinetics/lowe_et_al_2019.py
(likely temporary name - should be Pruppacher and Klett or Okuyama & Zung 1967 or alike?)
> adding Lowe et al. 2019 diffusion kinetics 

- PySDM/physics/constants_defaults.py
- PySDM/physics/saturation_vapour_pressure/__init__.py
- PySDM/physics/saturation_vapour_pressure/lowe1977.py
- tests/unit_tests/physics/test_saturation_vapour_pressure.py
> Add sat vap

- test-time-requirements.txt
- tests/smoke_tests/lowe_et_al_2019/test_fig_1.py
- tests/smoke_tests/lowe_et_al_2019/test_fig_2.py
- tests/smoke_tests/lowe_et_al_2019/test_surface_tension_models.py
- tests/smoke_tests/pyrcel/test_parcel_example.py
> add tests for pyrcel parcel example

- PySDM/dynamics/collisions/breakup_fragmentations/exponential.py
Small fix to address issue in PR136 of PySDM-examples
> Fix exp_frag backend call

- PySDM/dynamics/condensation.py
- test-time-requirements.txt
- tests/smoke_tests/shipway_and_hill_2012/test_few_steps.py
> an option to fix thd in condensation dynamics is added

- PySDM/backends/impl_numba/methods/collisions_methods.py
- tests/unit_tests/backends/test_collisions_methods.py
here's the relevant part of the paper:
(https://journals.ametsoc.org/view/journals/atsc/67/3/2009jas3175.1.xml?tab_body=pdf)
thanks @abulenok !
@edejong-caltech - let's aim for a unit test to cover it !
> fix typo in Straub et al. formulae (thanks @abulenok!)

- PySDM/backends/impl_numba/methods/collisions_methods.py
- tests/unit_tests/backends/test_collisions_methods.py
Building on the typo found by @abulenok , I found a few additional ones that we will want to correct in both CPU and GPU backends. All are noted on the open GPU PR as well.
> Fix a few typos in straub fragmentation backend

- PySDM/backends/impl_thrust_rtc/methods/collisions_methods.py
- PySDM/backends/impl_thrust_rtc/test_helpers/cpp2python.py
Makes flag_zero_multiplicity reusable from ThrustRTC C++ code
> Extract flag_zero_multiplicity logic for GPU into Commons C struct

- PySDM/physics/surface_tension/compressed_film_ruehl.py
Remove double assignment in compressed_film_ruehl
> Fix typo: remove double assignment

- PySDM/backends/impl_numba/methods/pair_methods.py
- tests/unit_tests/backends/test_pair_methods.py
handle properly the case when length<len(is_first_in_pair) this was already the case in the GPU backend
> Fix: set is_first_in_pair[working_length - 1] to False

- PySDM/backends/impl_numba/storage.py
- PySDM/backends/impl_thrust_rtc/storage.py
- PySDM/dynamics/collisions/breakup_efficiencies/constEb.py
- PySDM/dynamics/collisions/breakup_fragmentations/always_n.py
- PySDM/dynamics/collisions/breakup_fragmentations/straub2010.py
- PySDM/dynamics/collisions/coalescence_efficiencies/constEc.py
- PySDM/dynamics/collisions/coalescence_efficiencies/straub2010.py
- PySDM/dynamics/collisions/collision_kernels/constantK.py
This PR is related to https://github.com/open-atmos/PySDM/issues/976
> Replace uses of __setitem__ with fill for Storages. closes #1022

- test-time-requirements.txt
- tests/smoke_tests/srivastava_1982/test_eq_10.py
- tests/smoke_tests/srivastava_1982/test_eq_13.py
https://github.com/open-atmos/PySDM-examples/pull/210
> Add smoke tests for Srivastava 1982 eq10 and eq13

- tests/examples_tests/conftest.py
thanks @AgnieszkaMakulska for help with noticing it!
> fix paths in notebook/example discovery logic for example_tests

- PySDM/dynamics/collisions/breakup_fragmentations/feingold1988.py
- PySDM/dynamics/collisions/breakup_fragmentations/lowlist82.py
- PySDM/dynamics/collisions/breakup_fragmentations/slams.py
- PySDM/dynamics/collisions/breakup_fragmentations/straub2010.py
- examples/PySDM_examples/Abdul_Razzak_Ghan_2000/__init__.py
- examples/PySDM_examples/Alpert_and_Knopf_2016/__init__.py
- examples/PySDM_examples/Arabas_and_Shima_2017/__init__.py
- examples/PySDM_examples/Arabas_and_Shima_2017/example.py
- examples/PySDM_examples/Arabas_et_al_2015/__init__.py
- examples/PySDM_examples/Arabas_et_al_2023/__init__.py
- examples/PySDM_examples/Bartman_2020_MasterThesis/__init__.py
- examples/PySDM_examples/Bartman_et_al_2021/__init__.py
- examples/PySDM_examples/Berry_1967/__init__.py
- examples/PySDM_examples/Bieli_et_al_2022/__init__.py
- examples/PySDM_examples/Bulenok_2023_MasterThesis/__init__.py
- examples/PySDM_examples/Ervens_and_Feingold_2012/__init__.py
- examples/PySDM_examples/Grabowski_and_Pawlowska_2023/__init__.py
- examples/PySDM_examples/Jaruga_and_Pawlowska_2018/__init__.py
- examples/PySDM_examples/Kreidenweis_et_al_2003/__init__.py
- examples/PySDM_examples/Lowe_et_al_2019/__init__.py
- examples/PySDM_examples/Morrison_and_Grabowski_2007/__init__.py
- examples/PySDM_examples/Pyrcel/__init__.py
- examples/PySDM_examples/Shima_et_al_2009/__init__.py
- examples/PySDM_examples/Shima_et_al_2009/error_measure.py
- examples/PySDM_examples/Shipway_and_Hill_2012/__init__.py
- examples/PySDM_examples/Srivastava_1982/__init__.py
- examples/PySDM_examples/Szumowski_et_al_1998/__init__.py
- examples/PySDM_examples/Yang_et_al_2018/__init__.py
- examples/PySDM_examples/deJong_Mackay_et_al_2023/__init__.py
- examples/PySDM_examples/utils/__init__.py
+ link to Piotr Bartman's Master Thesis
> Add more links to examples and fragmentation functions docs

- examples/PySDM_examples/Shima_et_al_2009/example.py
thanks Brady Bhalla for pointing this out!
> removing obsolete code (TODO: add test depicting how to change terminal velocity formulation)

- .github/workflows/pdoc.yml
- .github/workflows/pypi.yml
- .github/workflows/tests.yml
- tests/examples_tests/test_tests_completeness.py
> CI workflows: do not run tests/examples on release (run only before and after merging); move pdoc and pypi workflows to separate .yml files

- .zenodo.json
update affiliation city and years. thanks @slayoo for adding this!
> Zenodo developers metadata update (affiliation city, years)

- setup.py
> add dependency on PySDM-examples and open-atmos-jupyter-utils packages

- examples/PySDM_examples/Rozanski_and_Sonntag_1982/figs_4_5_6.ipynb
aimed to help with the issue blocking #1507 and #1538
> assert helping to investigate R&S '82 example failures on Windows

- docs/bibliography.json
- examples/PySDM_examples/Bolin_1958/__init__.py
I hope it will fix missing link to this example in the documentation.
> Add description in init file in Bolin's example

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- .zenodo.json
- docs/bibliography.json
In bibliography there are duplicates, so I introduce a hook for it. 
Only thing is: maybe now we have to specify for other hooks type of files?
> New pre-commit hook: Check syntax of JSON files (e.g., if keys are not duplicated in bibliography.json or .zenodo.json)
